#Definición de directorios y paquterias
library(tidyverse)
library(lubridate)
library(sf)
library(readxl)
library(mapview)
library(stringdist)
library(stringi)
library(stringr)
library(kableExtra)
library(didimputation)
library(jsonify)
library(base)
library(stargazer)
library(lfe)
library(ISOweek)
library(mFilter)
path <- getwd()
datadir <- paste0(path,"/data/")
outputdir <- paste0(path,"/output/")